# Generated by Django 4.2.7 on 2023-12-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterUniqueTogether(
            name='workplace',
            unique_together={('plan', 'x', 'y')},
        ),
    ]
